#!/bin/bash
function readoutintname {
IFACE="$( bash <<EOF
ip route get 8.8.8.8 | sed -nr 's/.*dev ([^\ ]+).*/\1/p'
EOF
)"
}
function readoutprivkey {
PRIVATEKEY="$( bash <<EOF
sudo grep -w masternodeprivkey /root/.darkpaycoin$MASTERNODE/darkpaycoin.conf | cut -d'=' -f 2
EOF
)"
}


function deletemasternode {
		systemctl stop darkpaycoin$MASTERNODE.service
		rm -rf /root/.darkpaycoin$MASTERNODE 
		rm /usr/local/bin/darkpaycoind$MASTERNODE
}

function logmnserver {
		darkpaycoin-cli -datadir=/root/.darkpaycoin$i masternode status
		systemctl status darkpaycoin$i.service | grep Active
		tail -f .darkpaycoin$MASTERNODE/debug.log
}

function configure_systemd() {
		cat << EOF > /etc/systemd/system/$COIN_NAME.service
		[Unit]
		Description=$COIN_NAME service
		After=network.target
		[Service]
		User=root
		Group=root
		Type=forking
		#PIDFile=$CONFIGFOLDER/$COIN_NAME.pid
		ExecStart=$COIN_PATH$COIN_DAEMON -daemon -conf=$CONFIGFOLDER/$CONFIG_FILE -datadir=$CONFIGFOLDER
		ExecStop=-$COIN_PATH$COIN_CLI -conf=$CONFIGFOLDER/$CONFIG_FILE -datadir=$CONFIGFOLDER stop
		Restart=always
		PrivateTmp=true
		TimeoutStopSec=60s
		TimeoutStartSec=10s
		StartLimitInterval=120s
		StartLimitBurst=5
		[Install]
		WantedBy=multi-user.target
EOF

		  systemctl daemon-reload
		  sleep 3
		  systemctl start $COIN_NAME.service
		  systemctl enable $COIN_NAME.service >/dev/null 2>&1
		  if [[ -z "$(ps axo cmd:100 | egrep $COIN_DAEMON)" ]]; then
			echo -e "${RED}$COIN_NAME is not running${NC}, please investigate. You should start by running the following commands as root:"
			echo -e "${GREEN}systemctl start $COIN_NAME.service"
			echo -e "systemctl status $COIN_NAME.service"
			echo -e "less /var/log/syslog${NC}"
			exit 1
		 fi
}

function installmasternodescript {
			echo "Install script so you can run it like: darkcoin"
			cd /usr/local/bin
    			wget https://github.com/dennieboy96/darkcoin/raw/master/darkcoin
			chmod +x darkcoin
			chmod 755 darkcoin
}

function createmasternode {
if [[ ${#PRIVATEKEY} -ne "51" ]]; then
echo "The private key is shorter or longer than 51 characters, give a new one, use install masternode."
exit
else  
IP_ADDR="$( bash <<EOF
sudo cat /root/.IPV6
EOF
)"
				CONFIG_FILE='darkpaycoin.conf'
				CONFIGFOLDER=/root/.darkpaycoin$MASTERNODE
				COIN_NAME=darkpaycoin$MASTERNODE
				COIN_DAEMON=darkpaycoind$MASTERNODE
				COIN_PATH='/usr/local/bin/'
				COIN_CLI='darkpaycoin-cli'
				cp /root/darkpaycoind $COIN_PATH$COIN_DAEMON
				cp -R /root/.darkpaycoin-template/ /root/.darkpaycoin$MASTERNODE
				cp -R /root/.darkpaycoin/chainstate/ /root/.darkpaycoin$MASTERNODE/
				cp -R /root/.darkpaycoin/blocks/ /root/.darkpaycoin$MASTERNODE/
				cp  /root/.darkpaycoin/peers.dat /root/.darkpaycoin$MASTERNODE/
				chmod 775 /root/.darkpaycoin$MASTERNODE
				echo "bind=[$IP_ADDR$MASTERNODE]" >> /root/.darkpaycoin$MASTERNODE/darkpaycoin.conf
				echo "rpcport=100$MASTERNODE" >> /root/.darkpaycoin$MASTERNODE/darkpaycoin.conf
				echo "masternodeaddr=[$IP_ADDR$MASTERNODE:6667]" >> /root/.darkpaycoin$MASTERNODE/darkpaycoin.conf
				echo "masternodeprivkey=$PRIVATEKEY" >> /root/.darkpaycoin$MASTERNODE/darkpaycoin.conf

				configure_systemd
				sleep 10				
fi
}

function reinstallmasternode {
		MASTERNODE=$MASTERNODE
	echo "Are you sure want to reinstall masternode NR$MASTERNODE Y or N"
			read ANSWER
		case $ANSWER in
			"Y"|"y")
		readoutprivkey
		deletemasternode
		createmasternode
		logmnserver
		exit
		;;
			"N"|"n")
		exit		
		;;
	esac
}
case $1 in
	"-m"|"-M")
		MASTERNODE="$2";
		PRIVATEKEY="$3";
		createmasternode
		logmnserver
	exit
	;;
	
	"-log"|"-LOG")
		MASTERNODE="$2"
		echo "Which masternode do you want to log?"
			read MASTERNODE
		logmnserver
	exit		
	;;
	"-rm"|"-RM")
		MASTERNODE="$2"
		reinstallmasternode
	exit
	;;
	"-help"|"-h")
	echo "Manual: to delete a masternode use: darkcoin -dm 2, to create a masternode use -m, to log a masternode use -log, to reinstall a masternode use -rm"
	exit
	;;
	
	"-dm"|"-DM")
		MASTERNODE="$2"
		echo "Are you sure want to delete masternode NR$MASTERNODE Y or N"
		read ANSWER
	case $ANSWER in
		"Y"|"y")
		deletemasternode
	exit
	;;
		"N"|"n")
	exit		
	;;


esac
;;
	"")

PS3='Welcome back, what would you like to do?: '
options=("First config of VPS and masternode" "Roll out new masternode" "Reinstall masternode" "Delete masternode" "Start masternode" "Update masternode" "Statuscheck masternode" "Turn SWAP on" "Turn SWAP off"  )
select opt in "${options[@]}"
do

V61=2
GATE=1
	case $opt in
		"First config of VPS and masternode")
			echo "Put in IPv6 address without the last digit. Like this: 2a01:7c8:d000:3cc::"
				read IPVNET
			echo "IPv6 netmask"
				read NETMASK
			echo "Masternode server genkey"
				read PRIVATEKEY
			echo "How many masternodes will be on this server?"
				read AMMAS
			if [[ ${#PRIVATEKEY} -ne "51" ]]; then
			echo "The private key is shorter or longer than 51 characters, give a new one, use install masternode."
			exit
			else 
			readoutintname
			if [ -z $IFACE ]; then
			echo "there is no interface found, type network interface below:"
			read IFACE
			else  
			wget https://raw.githubusercontent.com/DarkPayCoin/releases/master/dpc_mn_install.sh
			sed -i "s|read -e COINKEY|COINKEY=$MNGENKEY|g" dpc_mn_install.sh
			bash dpc_mn_install.sh
			sed -i "/iface $IFACE inet6 auto/d" /etc/network/interfaces
			echo -e "\niface $IFACE inet6 static \n \t address $IPVNET$V61 \n \t netmask $NETMASK \n \t gateway $IPVNET$GATE \n \t dns-nameservers 2001:19f0:300:1704::6" >> /etc/network/interfaces

			for (( i = 3; i <= $AMMAS; i++ ))
				do
				echo -e "\t \t up ip -6 addr add $IPVNET$i/$NETMASK dev $IFACE \n \t \t down ip -6 addr add $IPVNET$i/$NETMASK dev $IFACE" >> /etc/network/interfaces
				done
					
			ifdown $IFACE
			ifup --ignore-errors $IFACE
			cd /root
			mkdir .darkpaycoin-template && chmod 775 .darkpaycoin-template
			cp .darkpaycoin/darkpaycoin.conf .darkpaycoin-template/
			sed -i '/rpcport=*/d; /masternodeaddr=/d; /masternodeprivkey=/d; /bind=/d;' /root/.darkpaycoin-template/darkpaycoin.conf
			sed -i "s/daemon=0/daemon=1/g" /root/.darkpaycoin-template/darkpaycoin.conf
			rm -rf /root/blocks /root/chainstate 
			rm /root/dpc_fastsync.zip
			rm /root/dpc_mn_install.sh
			echo "$IPVNET" > /root/.IPV6
			Echo "Install script so you can run it like: darkcoin"
			if [ ! -f /usr/local/bin/darkcoin ]; then
			installmasternodescript
			else
			rm /usr/local/bin/darkcoin
			installmasternodescript
			fi
			fi
			fi

	break

exit
;;
		"Roll out new masternode")
			echo "Masternode number"
				read MASTERNODE
			echo "Genkey of masternode"
				read PRIVATEKEY
			createmasternode
	break
exit
;;
		"Start masternode")
			echo "Masternode nummer van"
				read NMBR1
			echo "tot"
				read NMBR2
			 for (( i = $NMBR1; i <= $NMBR2; i++ ))			
			do
				echo "Starting node nr: $i"
				systemctl start darkpaycoin$i.service
			done
	break
exit
;;
		"Reinstall masternode")
			echo "Masternode number"
				read MASTERNODE
			reinstallmasternode
				
	break
exit
;;
		"Update masternode")
		       echo "Masternode nummer van"
                                read NMBRUP1
                        echo "tot"
                                read NMBRUP2

			if [ -d "/root/update" ]; then
				echo "download fastsync update"
				cd /root/update
				wget -N https://darkpaycoin.io/utils/dpc_fastsync.zip
				unzip -o dpc_fastsync.zip
				cd ..
			else
				echo "update directory maken"
				mkdir /root/update
				cd /root/update
				echo "download update"
				wget -N -q https://darkpaycoin.io/utils/dpc_fastsync.zip
				unzip -o dpc_fastsync.zip
				cd ..
			fi
			
			if [ "$NMBRUP1" -eq "0" ]; then
                        echo "Start updating daemon nr: 0"
                        systemctl stop darkpaycoin.service
                        rm -Rf /root/.darkpaycoin/blocks/
                        rm -Rf /root/.darkpaycoin/chainstate/
                        rm -Rf /root/.darkpaycoin/peers.dat
                        cp -R /root/update/blocks/ /root/.darkpaycoin/blocks/
                        cp -R /root/update/chainstate/ /root/.darkpaycoin/chainstate/
                        cp /root/update/peers.dat /root/.darkpaycoin/peers.dat
                        systemctl start darkpaycoin.service
                        echo "Done updating masternode nr: 0, wait 60sec to start-up"
                        sleep 60
                        NMBRUP1=2
			sed -i 's/addnode=136.243.185.4:6667/addnode=46.101.231.40:6667/' .darkpaycoin/darkpaycoin.conf
			sed -i 's/addnode=46.101.231.40:6667/addnode=128.199.198.131:6667/' .darkpaycoin/darkpaycoin.conf
			sed -i 's/addnode=67.99.220.116:6667/addnode=206.189.173.84:6667/' .darkpaycoin/darkpaycoin.conf
			sed -i 's/addnode=206.189.173.84:6667/addnode=138.68.108.10:6667/' .darkpaycoin/darkpaycoin.conf
                        fi

			for (( i = $NMBRUP1; i <= $NMBRUP2; i++ ))
			do
			echo "Start updating daemon nr: $i"
			systemctl stop darkpaycoin$i.service
			rm -Rf /root/.darkpaycoin$i/blocks/
			rm -Rf /root/.darkpaycoin$i/chainstate/
			rm -Rf /root/.darkpaycoin$i/peers.dat
			cp -R /root/update/blocks/ /root/.darkpaycoin$i/blocks/
			cp -R /root/update/chainstate/ /root/.darkpaycoin$i/chainstate/
			cp /root/update/peers.dat /root/.darkpaycoin$i/peers.dat
			systemctl start darkpaycoin$i.service
			echo "Done updating masternode nr: $i, wait 60sec to start-up"
			sleep 60
			sed -i 's/addnode=136.243.185.4:6667/addnode=46.101.231.40:6667/' .darkpaycoin$i/darkpaycoin.conf
   			sed -i 's/addnode=46.101.231.40:6667/addnode=128.199.198.131:6667/' .darkpaycoin$i/darkpaycoin.conf
 			sed -i 's/addnode=67.99.220.116:6667/addnode=206.189.173.84:6667/' .darkpaycoin$i/darkpaycoin.conf
    			sed -i 's/addnode=206.189.173.84:6667/addnode=138.68.108.10:6667/' .darkpaycoin$i/darkpaycoin.conf
			done
	break
exit
;;
		"Delete masternode")
			echo "Which masternodes needs to be deleted?"
                read MASTERNODE
				deletemasternode
	break
exit
;;
		"Turn SWAP on")
			echo "How big does the SWAP need to be give a number in GB?"
                                read SWAP1
			fallocate -l "$SWAP1"g /mnt/"$SWAP1"GiB.swap
			chmod 600 /mnt/"$SWAP1"GiB.swap
			mkswap /mnt/"$SWAP1"GiB.swap
			swapon /mnt/"$SWAP1"GiB.swap
			echo "/mnt/"$SWAP1"GiB.swap swap swap defaults 0 0" | sudo tee -a /etc/fstab
			echo "SWAP creation completed."
	break
exit
;;
                "Turn SWAP off")
                        echo "Are you sure to turn ALL the SWAP off? Y or N"
                                read SWAPOFF1
			case $SWAPOFF1 in
				"Y"|"y")
			swapoff -a
			rm -f /mnt/*GiB.swap
			sed -i '/GiB.swap/d' /etc/fstab
			exit
			;;
				"N"|"n")
			exit
			;;
			esac
        break
exit
;;
		"Statuscheck masternode")
			echo "Masternode nummer van"
				read NMBRSTAT1
			echo "tot"
				read NMBRSTAT2
			echo "node darkpaycoin nr0"
			darkpaycoin-cli -datadir=/root/.darkpaycoin masternode status
			systemctl status darkpaycoin$i.service | grep Active
			echo " "
			for (( i = $NMBRSTAT1; i <= $NMBRSTAT2; i++ ))
			do
				echo "node darkpaycoin nr$i"
				darkpaycoin-cli -datadir=/root/.darkpaycoin$i masternode status
				systemctl status darkpaycoin$i.service | grep Active		
			echo " "
			done
	break
exit
;;

esac
done
esac
